# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1644d622924c09f81ad448920d67a720c55128452a30c7d52b4c25ae06d89cd0b61245574660102c638a1dab538cfe17f9b72e5db6bc1b5a1e932e5782aafd43

test:
  secret_key_base: b0e0783dedcbbfc4e35819ad930951cbb5b8ddd3a9b4dd72d170d1737fe7298a7c8b7ee97e01cf3842b28722c422e902c6ec5923e1a387d188e7da85343b492d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
